import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

// ── Auto-update: version check ─────────────────────────────────────────────
// This is the most reliable way to force updates on ALL devices (iOS PWA,
// Android PWA, browser) regardless of Service Worker state.
//
// On every load + every 60s: fetches /version.json?t=<timestamp> (which
// bypasses ALL caches — browser HTTP cache, SW cache, CDN cache — because
// the query param is unique every time). If the server has a newer build than
// what's running, it forces window.location.reload().
//
// __BUILD_TIME__ is injected at build time by vite.config.ts (a number).
// version.json is generated by the vite plugin and deployed alongside the app.

declare const __BUILD_TIME__: number;

const checkForUpdate = async () => {
  try {
    const res = await fetch(`/version.json?t=${Date.now()}`, {
      cache: 'no-store',
      headers: { 'Cache-Control': 'no-cache' },
    });
    if (!res.ok) return;
    const data = await res.json();
    if (data.build && data.build > __BUILD_TIME__) {
      console.log(`[Update] New build detected (${data.build} > ${__BUILD_TIME__}). Reloading...`);
      window.location.reload();
    }
  } catch {
    // Offline or network error — silently ignore
  }
};

// Check immediately on load
checkForUpdate();

// Check every 60 seconds while the app is open
setInterval(checkForUpdate, 60_000);

// ── Service Worker ─────────────────────────────────────────────────────────
// Register SW for offline support. Do NOT unregister it — that was breaking
// the update mechanism on installed PWAs.
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/sw.js', { scope: '/', updateViaCache: 'none' })
    .then((reg) => {
      reg.update(); // Check for SW update immediately
      console.log('[SW] Registered:', reg.scope);
    })
    .catch((err) => console.warn('[SW] Registration failed:', err));
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
